In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Instalar librerias

In [ ]:
!pip install -U scikit-learn
!pip install nltk

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Collecting scikit-learn
  Downloading scikit_learn-1.4.0-1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 50.2 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.0,>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
Successfully installed scikit-learn-1.4.0
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)

# Procesamiento de NLP

## Explicación

### PROPUESTA DE UN PROCESO DE KDD

-----


- Autor: Ernesto Vladimir Palacios Merino.
- Asignatura: Minería de Datos - VIU 2023
- Fecha: 15-enero-2023


#### 1. Planteamiento del problema y objetivo a alcanzar


---



Se requiere realizar la clasificación de textos cortos, de alrededor de 300 caracteres, los cuales describen las actividades realizadas diariamente por los grupos de trabajo de la Empresa Eléctrica Regional del Sur (EERSSA).

El objetivo es entrenar una red neuronal supervisada que permita la clasificación del texto contenido en las actividades diarias.

##### Contexto:

Dentro de los procesos internos de la empresa eléctrica se realiza la elaboración mensual de informes de trabajo, describiendo el tipo de trabajos y el tiempo empleado en cada uno de ellos. Esta es una tarea que se la ha venido realizando de manera manual con papel y lápiz la cual buscamos automatizar.

#### 2. Elección de la base de datos y selección de datos útiles.


---


La fuente de datos para el desarrollo del presente proyecto se trata de los informes diarios de actividades, elaborados por cada grupo de trabajo, en el cual se detalla un breve resumen de la actividad, si esta ha sido planificada o no, el sector donde se interviene y el tiempo empleado.

El origen de éstos datos es **interno** y **estructurado**. Con el objetivo de realizar la clasificación automática de estas actividad se ha digitalizado el proceso manual de calificación durante el año 2023 hasta el mes de noviembre, se cuenta entonces con un **archivo en formato excel** `2023_CALIFICACION_ACTIVIDADES.xlsx` con todas las actividades realizadas por las cuadrillas ya clasificadas.

##### Selección de datos útiles

De acuerdo con la normativa institucional, las actuvidades deben clasificarse mediante la aplicación de un código llamado Cuenta Contable.

Ésta será nuestra variable objetivo: `CUENTA`

   - `511.04.001`: Actividades en las redes de distribución (postes).
   - `511.04.002`: Actividades del alumbrado público (lámparas).
   - `511.03.003`: Actividades de líneas de transmisión (Alta Tensión ⚠️⚡)
   - `511.05.001`: Actividades de acometidas hacia el cliente final.
   - `511.05.002`: Actividades de medidores eléctricos del cliente final.
   - `521.01.001`: Actividades de comercialización del servicio eléctrico.
   - `511.06.002`: Actividades de trabajos particulares solicitados por el cliente final.
   - `OT-01-2022-GECOM`: Instalación de un nuevo medidor de energía para el cliente final.
   - `OT-07-2022-GECOM`: Restitución, cambio de un medidor de energía para el cliente final.
   - `informativo`: Es el texto que no describe ninguna actividad sino que sirve para transmitir información hacia los superiores, puede ser informar de la ausencia de un trabajador por la solicitud de un permiso, o para informar que es un día festivo y que se labora en atención de daños, etc.
























> ![2023_ACTIVIDADES.jpg](https://drive.google.com/uc?id=1sMa7_9lWB_DAQ3heILvQgwOzCy4FLmPP)

 > ##### *Captura del archivo con la fuente de datos: `2023_CALIFICACION_ACTIVIDADES.xls`*

Dentro de las actividades diarias se describen algunas como: Trasnsporte y Alimentación, las cuales no se requiere su clasificación ya que se encuentran etiquetadas en los informes diarios de los trabajadores.

Aquellas tareas de tipo informativas se las puede identificar y descartar en base a que son tareas en las que no tienen la etiqueta de la red eléctrica en la que se interviene (`ALIMENTADOR`). Solo nos interesan aquellas actividades que se realizan en las redes eléctricas.

#### 3. Procesamiento y transformación de los datos.


---


Para el desarrollo de este proceso trabajaremos con texto, por lo tanto aplicaremos las siguientes transformaciones al texto con la finalidad normalizar y generalizar la solución desarrollada.

1. Cargar el archivo de excel al entorno de python en formato de Pandas Dataframe.
2. Eliminar aquellas filas con la etiqueta de alimentación y transporte.
3. Nos quedamos solo con las columnas `Cuenta` y `Actividad`

##### Transformaciones del texto.

1. Retirar acentos (diacritics) de las palabras. (ó ➡ o, á ➡ a).
2. Convertir todos los caracteres a minúsculas.
3. Convertir abreviaciones comunmente usadas por los grupos de Trabajo y mal escritas:

        a. est     ▶ estructura
        b. trafo   ▶ transformador
        c. breiker ▶ breaker
        d. med     ▶  medidor
        e. etc...
3. Remover palabras comunes `stop words`

# ACTIVIDAD 2 - DESARROLLO DEL MODELO PLANTEADO


## 4. Modelo de Minería de Datos.

----

El modelo ha aplicar se trata de un `Clasificador` mediante `Machine Learning supervisado` ya que contamos con un dataset previamente etiquetado.

Los pasos para obtener este modelo serán:

5. Tokenización
6. Lematización (steming)
7. División la base de datos para entrenamiento y validación: 80/20
8. Vectorizar el dataset para el entrenamiento. (n_gram_range = 2)
9. Tomar las 6~10 palabras más comunmente repetidas para cada categoria.
10. Entrenamiento de la red neuronal: `Multinomial Naive Bayes : MultinomialNB()`
11. Evaluar resultados.

## 5. Discusión e interpretación de los resultados.

----

#### Parámetros a considerar / modificar:
- El paso de lematización podría resultar adverso, o necesite ajustarlo.
- Se puede hacer pruebas modificando el parámetro `n_gramas_range` en el paso de verificación, si bien son comunes las frases:
    
        a. cambio tirafusible

        b. arreglo acometida

        c. arreglo luminaria
    
    puede resultar útil modificar este parámetro.

- Analizar el vector resultante para cada categoría, identificar palabras comunes o ambiguas para ser ignoradas y verificar si esto mejora el puntaje de nuestro clasificador.

- Considerar, probar usan un `vocabulario` propio con términos que tenemos la certeza de que se usa en cada categoría en el paso de vectorización, para lu cual consideraremos aquellos que de manera programática se han detectado como comunes a cada categoría.

- Explorar otros procesamientos de lenguaje natural (word2vec) y su posible implementación al problema.

Adicional a estas consideraciones, podemos valernos de otros campos (columnas) con los que se cuenta en el documento, sería interesante combinarlo con árboles de decisión, para obtener una mejor clasificación.

## Conclusiones:

Finalmente, la necesidad de la que surge este problema es la elaboración de informes mensuales, los cuales si o si deben estar correctamente clasificados todos sus actividades, por lo cual es importante que todas las actividades esten correctamente clasificadas. Eso quiere decir que el resultado del modelo siempre será revisado y corregido, en el caso de requerirlo, por personal calificado y conocedor del tema.

Esto significa que a medida que pasen los meses, tendremos una retroalimentación al sistema y un dataset con un mayor número de datos, lo que nos permitirá explorar técnicas diferentes y evaluar sus resultados.

Al tratarse de un dataset propio y un problema personal al que se enfrenta día a día. Se llevarán a cabo todos los pasos aqui descritos, si bien no se lo pudo llegar a completar en el tiempo dado para esta actividad, se continuará con el desarrollo y solución del problema aquí propuesto.

En atención a lo mencionado, se incluye al final, luego del análisis solicitado en las actividades, a forma de `anexo`, el código desarrollado para extraer la información de las Órdenes de trabajo diarias que elabora el personal, ya que la intención y uso final de este modelo de aprendizaje es utilizarlo mes a mes en las tareas que realizan los grupos de trabajo de la zona.



----

> *Referencias:*
- [YouTube: Text Classification with Python](https://youtu.be/EfEW3_RLnGA)
- [Medium: Multinomial NB](https://medium.com/@johnm.kovachi/implementing-a-multinomial-naive-bayes-classifier-from-scratch-with-python-e70de6a3b92e)

## Carga del archivo XLSX

Se ha guardado una copia del archivo excel en Google Drive para facilitar su carga:

In [ ]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gI-6Cu2raSGqbwnd7zW6s5qC7xEpQaU1' -O "2023_ACTIVIDADES.xlsx"

--2024-02-07 15:13:58--  https://docs.google.com/uc?export=download&id=1gI-6Cu2raSGqbwnd7zW6s5qC7xEpQaU1
Resolving docs.google.com (docs.google.com)... 142.250.101.138, 142.250.101.113, 142.250.101.101, ...
Connecting to docs.google.com (docs.google.com)|142.250.101.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gI-6Cu2raSGqbwnd7zW6s5qC7xEpQaU1&export=download [following]
--2024-02-07 15:13:58--  https://drive.usercontent.google.com/download?id=1gI-6Cu2raSGqbwnd7zW6s5qC7xEpQaU1&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.2.132, 2607:f8b0:4023:c0d::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.2.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3782213 (3.6M) [application/octet-stream]
Saving to: ‘2023_ACTIVIDADES.xlsx’

2023_ACTIVIDADES.xl 100%[===================>]   3.61M  21.3MB/s    in 0.2s

2024-02-07 15:14:02 (21.3 MB/s) - ‘2023_ACTIVIDADES.xlsx’ saved [3782213/3782213]

In [ ]:
# Carga del archivo en memoria.

import pandas as pd


path_actividades2023 = '/content/2023_ACTIVIDADES.xlsx'
xls_2023 = pd.ExcelFile( path_actividades2023 )
print( xls_2023.sheet_names )

['DB', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Hoja1']

La primera hoja 'DB' es una pequeña base de datos que se usa en Excel para facilitar al usuario el etiquetado de la información.

La última hoja, Hoja1, serían las actividades del mes de Diciembre, las cuales al momento de realización de este análisis no se encuentran listas en su totalidad, por lo tanto no las incluimos.

Desde Enero a  Noviembre todas las hojas tienen una estructura de columnas identicas y las que realizaremos la conversión a Dataframe para el posterior análisis.

In [ ]:
df_2023 = pd.DataFrame()

for hoja in range( 1, 11, 1):
    df_2023 = pd.concat( [ df_2023, pd.read_excel( xls_2023, hoja )], ignore_index = True )

df_2023.info()

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30433 entries, 0 to 30432
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CUENTA        23520 non-null  object
 1   EVENTO        24130 non-null  object
 2   ALIMENTADOR   29382 non-null  object
 3   TIPO          28177 non-null  object
 4   ACTIVIDAD     28169 non-null  object
 5   CUADRILLA     24130 non-null  object
 6   PRIMARIO      28177 non-null  object
 7   FECHA INICIO  24128 non-null  object
 8   FECHA FIN     24128 non-null  object
 9   H:MM          24130 non-null  object
 10  EXTRA         28137 non-null  object
 11  DESCONEX      28169 non-null  object
 12  ID            24130 non-null  float64
 13  RESPONSABLE   24130 non-null  object
 14  VEHICULO      24130 non-null  object
 15  LUGAR         24130 non-null  object
 16  PDF           24130 non-null  object
dtypes: float64(1), object(16)
memory usage: 3.9+ MB

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

### Analisis exploratorio 1.
Es necesario eliminar del dataset filas vacias que se importan desde excel, se eliminan las filas que no tengan texto en la columna `EVENTO`.

In [ ]:
df_2023 = df_2023[df_2023.EVENTO.notnull()] #elimina filas de evento sin texto
print( "Número de filas = " + str(len(df_2023)) )
df_2023[['CUENTA','EVENTO','ALIMENTADOR','TIPO']].query( 'CUENTA == " "' ).sample(10)

Número de filas = 24130

,CUENTA,EVENTO,ALIMENTADOR,TIPO
19914,,Se elabora la Orden de trabajo y se carga las...,,RUTINARIA
7640,,Traslado desde Los Hachales hasta la agencia ...,,TRANSPORTE
15322,,"Desde San Pablo, nos trasladamos hacia la Age...",,TRANSPORTE
4244,,Taller de la EERSSA Loja se deja el vehiculo ...,,RUTINARIA
12266,,"Desde Santa Rita, nos trasladamos hacia la Ag...",,TRANSPORTE
19908,,LUNCH EN EL SECTOR DE EL IDEAL.,,ALIMENTACION
7576,,Centro de control informa de daño traslado a ...,,TRANSPORTE
24622,,"En la Agencia Zamora, se realiza labores admi...",,RUTINARIA
21310,,LUNCH EN ZAMORA,,ALIMENTACION
26438,,Traslado a Namirez,,TRANSPORTE

### Análisis exploratorio 2.
Existe una gran cantidad de actividades que no tienen una cuenta asociada, esto se debe a que son actividades de tipo: transporte, alimentación, informativas. Por lo tanto presindiremos de estas actividades.

In [ ]:
df_2023 = df_2023[df_2023.CUENTA != ' ']

### Análisis exploratorio 3.

Agrupamos y contamos las columna `CUENTAS` para tener una idea de los datos con los que contamos.

Observamos que hay cuatro cuentas que tienen un muy bajo conteo, esto se debe a que se tratan de tareas específicas realizadas por grupos de trabajo que no se encuentran dentro de los considerados en el área de influencia de los datos recolectados. Su existencia sugiere que se ha colaborado pero no es una tarea diaria.

El entrenar la red neuronal con una categoría ta dispareja puede ser una desventaja, una mejor alternativa puede ser el aplicar otro tipo de análisis estardístico para poder clasificar estos casos, posiblemente un árbol de decisión.

Por lo tanto guardaremos en un dataset diferente éstas cuentas con el fin de más adelante volver a realizar el proceso iterativo de KDD e integrarles a nuestro análisis.

In [ ]:
print( df_2023.groupby( 'CUENTA' )['EVENTO'].nunique() )

CUENTA
511.03.003            24
511.04.001          5520
511.04.002          1718
511.05.001          1411
511.05.002          1021
521.01.001           159
OT-01-2022-GECOM     277
OT-07-2022-GECOM       8
Name: EVENTO, dtype: int64

In [ ]:
"""
 Guardamos las actividades de 'baja frecuencia' en un dataset diferente.
"""

df_ActividadBajaFreq = df_2023.query( "CUENTA ==  '511.03.003' or CUENTA == '521.01.001' or CUENTA == 'OT-01-2022-GECOM' or CUENTA == 'OT-07-2022-GECOM' " )

In [ ]:
"""
 Continuamos el análisis con los datos restantes.
"""

df_data = df_2023[ df_2023['CUENTA'] != '511.03.003' ][ df_2023['CUENTA'] != '521.01.001' ][ df_2023['CUENTA'] != 'OT-01-2022-GECOM' ][ df_2023['CUENTA'] != 'OT-07-2022-GECOM' ]

<ipython-input-12-216577e13c0c>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_data = df_2023[ df_2023['CUENTA'] != '511.03.003' ][ df_2023['CUENTA'] != '521.01.001' ][ df_2023['CUENTA'] != 'OT-01-2022-GECOM' ][ df_2023['CUENTA'] != 'OT-07-2022-GECOM' ]

In [ ]:
print( df_data.groupby( 'CUENTA' )['EVENTO'].nunique() )

CUENTA
511.04.001    5520
511.04.002    1718
511.05.001    1411
511.05.002    1021
Name: EVENTO, dtype: int64

Ahora tenemos un dataset mejor balanceado, sin embargo la cuenta `511.04.001` sigue siendo mayor a las demás,lo cual puede culminar en que se sobreaprenda esta etiqueta, para balancear de mejor manera podemos reducir los items de este tipo.

In [ ]:
df_balanced = df_data.drop(df_data[df_data['CUENTA'] == '511.04.001'].sample(frac=.65).index)
df_balanced = df_balanced[df_balanced['CUENTA'].notna()]
df_balanced = df_balanced[['CUENTA','EVENTO']]
df_balanced = df_balanced.reset_index()

### Resultado de la limpieza de datos

In [ ]:
print( df_balanced.groupby( 'CUENTA' )['index'].nunique() )

CUENTA
511.04.001    1946
511.04.002    1736
511.05.001    1427
511.05.002    1028
Name: index, dtype: int64

In [ ]:
df_balanced.to_pickle( '/content/drive/MyDrive/Colab_Disk/NLTK/df_excel_main.pkl' )
df_ActividadBajaFreq.to_pickle( '/content/drive/MyDrive/Colab_Disk/NLTK/df_excel_gecom.pkl' )

## Cargar datos convertidos desde Excel

In [ ]:
df_balanced = pd.read_pickle('/content/drive/MyDrive/Colab_Disk/NLTK/df_excel_main.pkl')
df_ActividadBajaFreq = pd.read_pickle( '/content/drive/MyDrive/Colab_Disk/NLTK/df_excel_gecom.pkl' )

## TRANSFORMACIONES DEL TEXTO

### 1. Remover acentos. (Diacritics)

> Referencia: [pandas.Series.str.normalize](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.normalize.html)

Usamos la función normalize() de Pandas para retirar los acentos.

### 2. Texto en minusculas

> Referencia: [pandas.Series.str.lower](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.lower.html)

Usamos la función lower()


### 3. Reemplazar palabras (abreviaciones)
> Referencia: [replace words in pandas using dictionary ](https://stackoverflow.com/questions/48824890/replace-words-in-pandas-dataframe-using-dictionary)

In [ ]:
df_balanced['transformacion_1'] = (df_balanced['EVENTO']      # 1. Remover acentos
                                    .str.normalize('NFKD')
                                    .str.encode('ascii', errors='ignore')
                                    .str.decode('utf-8')

                                    .str.lower()           # 2. Texto en minuscula
                                    )
df_balanced.sample(10)

,index,CUENTA,EVENTO,transformacion_1
776,4194,511.04.001,"DIA FESTIVO ""LUNES DE CARNAVAL"" - Se permanec...","dia festivo ""lunes de carnaval"" - se permanec..."
1474,9673,511.05.002,En La Paz en la Estructura 39152 se revisa y ...,en la paz en la estructura 39152 se revisa y ...
933,6250,511.04.001,"En el Progreso, Estructura 28706 se coordina ...","en el progreso, estructura 28706 se coordina ..."
335,1434,511.04.001,"La Independencia, Estructura 29590-29591 LMT3...","la independencia, estructura 29590-29591 lmt3..."
3461,19663,511.04.001,En la calle Eloy Alfaro en la est 071739 se ...,en la calle eloy alfaro en la est 071739 se ...
3486,19828,511.05.001,En el sector de La Gruta en la est 043041 se...,en el sector de la gruta en la est 043041 se...
4961,26289,511.05.001,En Namirez se realiza inspeccion para Cambio ...,en namirez se realiza inspeccion para cambio ...
4649,24864,511.04.002,RECLAMO No. 1100492533. Yantzaza en el barrio...,reclamo no. 1100492533. yantzaza en el barrio...
3220,18567,511.05.002,Zamora barrio La Peninsula en la Estructura N...,zamora barrio la peninsula en la estructura n...
4596,24774,511.04.002,"Gualaquiza Flor del Bosque, En la Estructura ...","gualaquiza flor del bosque, en la estructura ..."

In [ ]:
"""
   Definición de palabras a reemplzarzar
   Esta lista se irá ampliando de manera iterativa.

"""
palabras = {
		"#"             : " ",
		"est"           : "estructura",
		"est."          : "estructura",
		"est."          : "estructura",
		"estructuras"   : "estructura",
		"poste"         : "estructura",
		"ingnitor"      : "ignitor",
		"w na"          : "wna",
		"70 w"          : "70w",
		"100 w"         : "100w",
		"150 w"         : "150w",
		"70 wna"        : "70wna",
		"70w na"        : "70wna",
		"70 w na"       : "70wna",
		"100 wna"       : "100wna",
		"100w na"       : "100wna",
		"100 w na"      : "100wna",
		"150 wna"       : "150wna",
		"150w na"       : "150wna",
		"150 w na"      : "150wna",
		"tiraf"         : "tirafusible",
		"med."          : "medidor",
		"med"           : "medidor",
		"medidores"     : "medidor",
		"cc"            : "Centro de Control",
		"cc."           : "Centro de Control",
		"cc,"           : "Centro de Control",
		"trafo"         : "transformador",
		"tranfo"        : "transformador",
		"breiker"       : "breaker",
		"  "             : " ",
	}

reemplazar = {r'(\b){}(\b)'.format(k):r'\1{}\2'.format(v) for k,v in palabras.items()}
reemplazar

{'(\\b)#(\\b)': '\\1 \\2',
 '(\\b)est(\\b)': '\\1estructura\\2',
 '(\\b)est.(\\b)': '\\1estructura\\2',
 '(\\b)estructuras(\\b)': '\\1estructura\\2',
 '(\\b)poste(\\b)': '\\1estructura\\2',
 '(\\b)ingnitor(\\b)': '\\1ignitor\\2',
 '(\\b)w na(\\b)': '\\1wna\\2',
 '(\\b)70 w(\\b)': '\\170w\\2',
 '(\\b)100 w(\\b)': '\\1100w\\2',
 '(\\b)150 w(\\b)': '\\1150w\\2',
 '(\\b)70 wna(\\b)': '\\170wna\\2',
 '(\\b)70w na(\\b)': '\\170wna\\2',
 '(\\b)70 w na(\\b)': '\\170wna\\2',
 '(\\b)100 wna(\\b)': '\\1100wna\\2',
 '(\\b)100w na(\\b)': '\\1100wna\\2',
 '(\\b)100 w na(\\b)': '\\1100wna\\2',
 '(\\b)150 wna(\\b)': '\\1150wna\\2',
 '(\\b)150w na(\\b)': '\\1150wna\\2',
 '(\\b)150 w na(\\b)': '\\1150wna\\2',
 '(\\b)tiraf(\\b)': '\\1tirafusible\\2',
 '(\\b)med.(\\b)': '\\1medidor\\2',
 '(\\b)med(\\b)': '\\1medidor\\2',
 '(\\b)medidores(\\b)': '\\1medidor\\2',
 '(\\b)cc(\\b)': '\\1Centro de Control\\2',
 '(\\b)cc.(\\b)': '\\1Centro de Control\\2',
 '(\\b)cc,(\\b)': '\\1Centro de Control\\2',
 '(\\b)trafo(\\b)': '\\1transformador\\2',
 '(\\b)tranfo(\\b)': '\\1transformador\\2',
 '(\\b)breiker(\\b)': '\\1breaker\\2',
 '(\\b)  (\\b)': '\\1 \\2'}

#### operación de reemplazo con regex

In [ ]:
df_balanced['correcciones'] = df_balanced['transformacion_1'].replace( reemplazar, regex=True)
df_balanced['correcciones'] = df_balanced['correcciones'].str.replace('[^\w\s]','',regex=True) # Remover puntuacucion . ,
df_balanced.sample(10)

,index,CUENTA,EVENTO,transformacion_1,correcciones,tokens,reduccion
2957,17802,511.05.001,Se traslada de Catacocha a Pachicutza est# 31...,se traslada de catacocha a pachicutza est# 31...,se traslada de catacocha a pachicutza estruct...,"[se, traslada, de, catacocha, a, pachicutza, e...","[traslada, catacocha, pachicutza, 31530, senor..."
3003,17879,511.05.002,Barrio San Roque a Barrio El Paraiso est 178...,barrio san roque a barrio el paraiso est 178...,barrio san roque a barrio el paraiso estructu...,"[barrio, san, roque, a, barrio, el, paraiso, e...","[barrio, san, roque, barrio, paraiso, 178813, ..."
5101,26740,511.05.001,"En Union Lojana Sra. Eugenia Toledo, Medidor ...","en union lojana sra. eugenia toledo, medidor ...",en union lojana sra eugenia toledo medidor 10...,"[en, union, lojana, sra, eugenia, toledo, medi...","[union, lojana, sra, eugenia, toledo, medidor,..."
1334,8078,511.04.001,En el centro de Gualaquiza se realiza revisio...,en el centro de gualaquiza se realiza revisio...,en el centro de gualaquiza se realiza revisio...,"[en, el, centro, de, gualaquiza, se, realiza, ...","[centro, gualaquiza, realiza, revision, lmt, v..."
5071,26683,511.05.001,"En San Francisco, Sra. Nancy Ortiz, Orden, 38...","en san francisco, sra. nancy ortiz, orden, 38...",en san francisco sra nancy ortiz orden 381961...,"[en, san, francisco, sra, nancy, ortiz, orden,...","[san, francisco, sra, nancy, ortiz, orden, 381..."
3799,21967,511.04.001,En Tanques de Agua en la Estructura 31186 se ...,en tanques de agua en la estructura 31186 se ...,en tanques de agua en la estructura 31186 se ...,"[en, tanques, de, agua, en, la, estructura, 31...","[tanques, agua, 31186, encuentra, tirafusible,..."
1133,6972,511.04.001,En Corralpamba en la Estructura 219845 se enc...,en corralpamba en la estructura 219845 se enc...,en corralpamba en la estructura 219845 se enc...,"[en, corralpamba, en, la, estructura, 219845, ...","[corralpamba, 219845, encuentra, luminaria, 10..."
3298,18699,511.04.002,Nos trasladamos desde el sector de Barrio Chi...,nos trasladamos desde el sector de barrio chi...,nos trasladamos desde el sector de barrio chi...,"[nos, trasladamos, desde, el, sector, de, barr...","[trasladamos, sector, barrio, chichis, parroqu..."
1279,7781,511.05.002,DAÑO REPORTADO POR Centro de Control (Mensaje...,dano reportado por centro de control (mensaje...,dano reportado por centro de control mensaje ...,"[dano, reportado, por, centro, de, control, me...","[dano, reportado, centro, control, mensaje, wh..."
2142,13394,511.04.001,Estructura 34749 revisa transformador 25KVA s...,estructura 34749 revisa transformador 25kva s...,estructura 34749 revisa transformador 25kva s...,"[estructura, 34749, revisa, transformador, 25k...","[34749, revisa, transformador, 25kva, sicap, 1..."

### 4. Remover palabras comunes (stop words)
> Referencia: [remove stop words](https://www.educative.io/answers/how-to-remove-stop-words-with-nltk-library-in-python)

In [ ]:
import nltk

nltk.download('stopwords')
nltk.download('punkt')
stopword_es = nltk.corpus.stopwords.words('spanish')
stopword_es.append( 'estructura' ) # es comun a todas las cuentas

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
def remove_stopwords(text):
    text = [word for word in text if word not in stopword_es]
    return text

In [ ]:
df_balanced['tokens'] = df_balanced['correcciones'].apply(lambda x: nltk.tokenize.word_tokenize(x))
df_balanced.sample(10)

,index,CUENTA,EVENTO,transformacion_1,correcciones,tokens,reduccion
1065,6747,511.04.002,"Zamora barrio Santa Elena, via a Romerillos e...","zamora barrio santa elena, via a romerillos e...",zamora barrio santa elena via a romerillos en...,"[zamora, barrio, santa, elena, via, a, romeril...","[zamora, barrio, santa, elena, via, romerillos..."
4146,23498,511.05.002,En Tunantza se revisa daño por variacion de V...,en tunantza se revisa dano por variacion de v...,en tunantza se revisa dano por variacion de v...,"[en, tunantza, se, revisa, dano, por, variacio...","[tunantza, revisa, dano, variacion, voltaje, m..."
1141,7016,511.05.001,En El Puerto por informacion de los moradores...,en el puerto por informacion de los moradores...,en el puerto por informacion de los moradores...,"[en, el, puerto, por, informacion, de, los, mo...","[puerto, informacion, moradores, encuentra, ac..."
4455,24163,511.05.002,"Gualaquiza, Cuenca y Garcia Moreno, est #0429...","gualaquiza, cuenca y garcia moreno, est #0429...",gualaquiza cuenca y garcia moreno estructura ...,"[gualaquiza, cuenca, y, garcia, moreno, estruc...","[gualaquiza, cuenca, garcia, moreno, 042993, i..."
2361,15399,511.04.001,"En Zamora, se realiza inspeccion de Fibras Op...","en zamora, se realiza inspeccion de fibras op...",en zamora se realiza inspeccion de fibras opt...,"[en, zamora, se, realiza, inspeccion, de, fibr...","[zamora, realiza, inspeccion, fibras, opticas,..."
301,1221,511.04.001,Atencion de reclamos de Centro de Control (No...,atencion de reclamos de centro de control (no...,atencion de reclamos de centro de control no ...,"[atencion, de, reclamos, de, centro, de, contr...","[atencion, reclamos, centro, control, programa..."
1704,10637,511.04.001,"En Tutus Estructura 237263, se encuentra fusi...","en tutus estructura 237263, se encuentra fusi...",en tutus estructura 237263 se encuentra fusib...,"[en, tutus, estructura, 237263, se, encuentra,...","[tutus, 237263, encuentra, fusible, quemado, d..."
1187,7214,511.04.002,"Reclamo Nro. 199488951, En Cuje Estructura 66...","reclamo nro. 199488951, en cuje estructura 66...",reclamo nro 199488951 en cuje estructura 6629...,"[reclamo, nro, 199488951, en, cuje, estructura...","[reclamo, nro, 199488951, cuje, 66298, arregla..."
1799,12214,511.04.001,"En Timbara, Estructura 71958 se realiza excav...","en timbara, estructura 71958 se realiza excav...",en timbara estructura 71958 se realiza excava...,"[en, timbara, estructura, 71958, se, realiza, ...","[timbara, 71958, realiza, excavacion, hueco, c..."
5659,28378,511.04.001,Se continua con vestida y regulada de Estruct...,se continua con vestida y regulada de estruct...,se continua con vestida y regulada de estruct...,"[se, continua, con, vestida, y, regulada, de, ...","[continua, vestida, regulada, 1cdv, 1ed1er1er,..."

In [ ]:
df_balanced['reduccion'] = df_balanced['tokens'].apply(lambda x: remove_stopwords(x))
df_balanced.sample(10)

,index,CUENTA,EVENTO,transformacion_1,correcciones,tokens,reduccion
1272,7738,511.04.001,En La Argelia Estructura 127344 se arregla un...,en la argelia estructura 127344 se arregla un...,en la argelia estructura 127344 se arregla un...,"[en, la, argelia, estructura, 127344, se, arre...","[argelia, 127344, arregla, vano, neutro, arran..."
5444,27721,511.04.001,"Zamora, sector La Peninsula se toma fotos a d...","zamora, sector la peninsula se toma fotos a d...",zamora sector la peninsula se toma fotos a de...,"[zamora, sector, la, peninsula, se, toma, foto...","[zamora, sector, peninsula, toma, fotos, deriv..."
3867,22232,511.05.002,"El Guayabal, se revisa Medidor 205105 se encu...","el guayabal, se revisa medidor 205105 se encu...",el guayabal se revisa medidor 205105 se encue...,"[el, guayabal, se, revisa, medidor, 205105, se...","[guayabal, revisa, medidor, 205105, encuentra,..."
1804,12244,511.04.001,"En la Troncal Amazonica, Estructura 27845 con...","en la troncal amazonica, estructura 27845 con...",en la troncal amazonica estructura 27845 conj...,"[en, la, troncal, amazonica, estructura, 27845...","[troncal, amazonica, 27845, conjuntamente, per..."
3470,19701,511.04.001,Enel sector de Guabi Bajo se realiza tala de ...,enel sector de guabi bajo se realiza tala de ...,enel sector de guabi bajo se realiza tala de ...,"[enel, sector, de, guabi, bajo, se, realiza, t...","[enel, sector, guabi, bajo, realiza, tala, arb..."
3836,22079,511.04.001,En Nueva Vida en la Estructura 39057 se encue...,en nueva vida en la estructura 39057 se encue...,en nueva vida en la estructura 39057 se encue...,"[en, nueva, vida, en, la, estructura, 39057, s...","[nueva, vida, 39057, encuentra, bloqueado, tra..."
4046,23220,511.05.001,En el sector de Sevilla en la est 92117 se r...,en el sector de sevilla en la est 92117 se r...,en el sector de sevilla en la estructura 9211...,"[en, el, sector, de, sevilla, en, la, estructu...","[sector, sevilla, 92117, realiza, arreglo, aco..."
5443,27709,511.05.001,DAÑO REPORTADO POR Centro de Control Quebrada...,dano reportado por centro de control quebrada...,dano reportado por centro de control quebrada...,"[dano, reportado, por, centro, de, control, qu...","[dano, reportado, centro, control, quebrada, c..."
1024,6645,511.05.002,Por pedido del señor Manuel Gualan. En El Kim...,por pedido del senor manuel gualan. en el kim...,por pedido del senor manuel gualan en el kimi...,"[por, pedido, del, senor, manuel, gualan, en, ...","[pedido, senor, manuel, gualan, kimi, no30683,..."
3480,19773,511.04.001,En El Belen Alto en la est 501859 se realiza...,en el belen alto en la est 501859 se realiza...,en el belen alto en la estructura 501859 se r...,"[en, el, belen, alto, en, la, estructura, 5018...","[belen, alto, 501859, realiza, revision, lbt, ..."

## Guardar y Cargar el Dataset balanceado

- Hasta este punto tenemos un dataset "balanceado" en las cantidades de eventos de cada cuenta.

In [ ]:
df = df_balanced.reindex()
df = df[['CUENTA', 'reduccion']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6137 entries, 0 to 6136
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CUENTA     6137 non-null   object
 1   reduccion  6137 non-null   object
dtypes: object(2)
memory usage: 96.0+ KB

In [ ]:
"""
    Guardamos el Archivo procesado hasta este punto en un formato PICKLE

"""

df.to_pickle( '/content/drive/MyDrive/Colab_Disk/NLTK/tokes_2023_v1.pkl' )

# IMPLEMENTACIÓN DEL MODELO:

A partir de este punto es posible implementar el/los modelos de clasificación del tipo de cuenta en base al texto descriptivo de la actividad.

Aún se necesario un mayor y mejor análisis exploratorio para contar con datos aún más precisos.

In [ ]:
df = pd.read_pickle( '/content/drive/MyDrive/Colab_Disk/NLTK/tokes_2023_v1.pkl' )
df.sample(5)

          CUENTA                                          reduccion
2078  511.04.001  [coordina, centro, control, cumplir, plan, ope...
4795  511.04.001  [vez, colocado, puntos, referencia, distancia,...
2225  511.04.001  [guismi, 28482, 28483, realiza, corte, palmera...
2462  511.04.002  [13, guaguaymi, bajo, no179707, arregla, 1, lu...
1017  511.04.002  [reclamo, 199484999, yantzaza, barrio, piedra,...

### Convertir el Dataframe en Lista

In [ ]:
# Unir tokens por lista

from collections import Counter

def flatten_comprehension(matrix):
    return [item for row in matrix for item in row]

df_tokens = df.groupby( 'CUENTA')['reduccion'].agg(list).reset_index(name = 'tokens' )
df_tokens['palabras'] = df_tokens['tokens'].apply( lambda token: flatten_comprehension(token) )
df_tokens = df_tokens[['CUENTA','palabras']]
df_tokens['frecuencia'] = df_tokens['palabras'].apply(Counter)
df_tokens['palabras_freq'] = df_tokens['frecuencia'].apply( lambda item: item.most_common(50) )
df_tokens[['CUENTA','palabras_freq']]

       CUENTA                                      palabras_freq
0  511.04.001  [(realiza, 706), (encuentra, 703), (transforma...
1  511.04.002  [(1, 1766), (ocupa, 1434), (luminaria, 1397), ...
2  511.05.001  [(medidor, 1556), (acometida, 867), (realiza, ...
3  511.05.002  [(medidor, 983), (servicio, 534), (breaker, 38...

In [ ]:
fila = df_tokens['frecuencia'][3]
fila.most_common(50)

[('medidor', 983),
 ('servicio', 534),
 ('breaker', 384),
 ('realiza', 320),
 ('revisa', 316),
 ('conexiones', 234),
 ('inspeccion', 231),
 ('nuevo', 223),
 ('dano', 197),
 ('encuentra', 193),
 ('cliente', 163),
 ('pangui', 127),
 ('centro', 125),
 ('cambia', 124),
 ('electrico', 120),
 ('control', 118),
 ('traslado', 118),
 ('sr', 113),
 ('ajusta', 112),
 ('normal', 108),
 ('reportado', 106),
 ('instalacion', 99),
 ('sra', 97),
 ('san', 95),
 ('nro', 92),
 ('mal', 88),
 ('ocasional', 79),
 ('traslada', 79),
 ('normaliza', 72),
 ('queda', 71),
 ('falla', 68),
 ('barrio', 67),
 ('senor', 67),
 ('atender', 64),
 ('labora', 63),
 ('voltaje', 62),
 ('zamora', 61),
 ('calle', 60),
 ('interno', 59),
 ('lectura', 58),
 ('gualaquiza', 58),
 ('reconecta', 56),
 ('acometida', 56),
 ('informa', 56),
 ('trasladamos', 56),
 ('borneras', 55),
 ('tx6', 54),
 ('c', 54),
 ('hace', 53),
 ('caja', 51)]

## Divison del set en Train y Test

In [ ]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

## Hasta este punto hemos llegado en la transformación de los datos.

Contamos con un dataset de tokens para entrenamiento y otro para testeso de resultado, los siguientes pasos:

- vectorizer.fit
- naive_bayes_classifier
- evaluate_classifier

Quedan pendientes su implementación.