# TIME SERIES ANALYSIS

In [1]:
import sys
import time
from pathlib import Path
import pandas as pd
import logging
from deltalake import DeltaTable, write_deltalake
from pprint import pprint
from datetime import datetime

logging.basicConfig(level=logging.INFO)

DELTA_TABLE_PATH_ON_HOST = "/home/vlad/delta_V30"

table_path = DELTA_TABLE_PATH_ON_HOST

Success!!!

## Conexión con Delta Lake en local

In [14]:
# Verify the existence of the DELTA LAKE table
if not DeltaTable.is_deltatable(table_path):
    print(
        f"No se ha encontrado la base de datos PARQUET-DELTALAKE en la direccion:\n NO_DELTA_LAKE en: {table_path}" )
else:
    dt = DeltaTable(table_path)
    df = dt.to_pandas()
    print(f"Conectado a la tabla Delta Lake en: {table_path}")

Conectado a la tabla Delta Lake en: /home/vlad/delta_V30

### Filtrado del Alimentador Zamora 1

In [18]:
z1_df = df.query( f" Alimentador == 'Zamora I' and Cuenta == 'REDES' and (Tipo == 'CORRECTIVO' or Tipo == 'PREVENTIVO')" )
z1_df

,Item,Cuenta,Evento,Actividad,Alimentador,Primario,Desconexion,SIG,Tipo,Materiales,...,InicioEvento,FinEvento,Duracion,Responsable,Colaboradores,HorasExtra,Vehiculo,Sitio,id_ot,Archivo
17,5,REDES,Cumbaratza en la estructura. 27803 se revisa ...,PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-03-24 11:30:00,2025-03-24 12:30:00,60,MORALES RIVERA LUIS ALBERTO,3,No,2-91,"Zamora, Paquisha",149726,OT [02] Alumbrado Zamora 2025-03-24 (012) LM.pdf
40,6,REDES,Zamora: estructura. # 27295-27296 se coloca un...,PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2025-08-26 14:45:00,2025-08-26 15:55:00,70,AGURTO BARRAGAN LUIS DARWIN,4,No,2-45,Yantzaza - Zamora.,159852,OT [05] Energizados Yantzaza 2025-08-26 (0) LA...
113,6,REDES,Zamora calle Podocarpus se aploma estructura....,NO PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2020-12-08 10:00:00,2020-12-08 11:40:00,100,MORALES RIVERA LUIS ALBERTO,2,No,R-29,"Zamora, Vía antigua a Loja",57356,OT [01] Cuadrilla Zamora 2020-12-08 (012) LM.pdf
124,4,REDES,"En El Limón, conjuntamente con la Cuadrilla de...",PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2023-01-06 11:30:00,2023-01-06 13:00:00,90,RIOS RIOS FRANCISCO FERNANDO,3,No,2-110,"Zamora, La Toquilla - La Fragancia, El Limón",99572,OT [01] Cuadrilla Zamora 2023-01-06 (006) FR.pdf
197,14,REDES,"DAÑO REPORTADO POR Centro de Control, Av. Hér...",NO PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2023-09-21 19:30:00,2023-09-21 20:36:00,66,RIOS RIOS FRANCISCO FERNANDO,3,Si,2-110,Zamora,115295,OT [01] Cuadrilla Zamora 2023-09-21 (006) FR.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396713,4,REDES,"DAÑO REPORTADO POR Centro de Control, Puente ...",NO PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-09 10:40:00,2025-10-09 12:45:00,125,RIOS RIOS FRANCISCO FERNANDO,1,No,2-110,"Zamora, El Queque.",162961,OT [01] Cuadrilla Zamora 2025-10-09 (006) FR.pdf
396833,3,REDES,En el El Oso vía a Podocarpus en conjunto con ...,PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2025-10-14 08:45:00,2025-10-14 13:00:00,255,JARA NARVAEZ GALO SILVERIO,2,No,2-111,Zamora,163150,OT [21] Agencia Zamora 2025-10-14 (050) GJ.pdf
397241,16,REDES,"Zamora en la calle Podocarpus, Avenida Alonso...",NO PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2025-10-08 21:32:00,2025-10-08 23:07:00,95,MORALES RIVERA LUIS ALBERTO,1,Si,R-159,Namirez,162895,OT [02] Alumbrado Zamora 2025-10-08 (012) LM.pdf
397379,2,REDES,"DAÑO REPORTADO POR Centro de Control, Santa E...",NO PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-19 12:15:00,2025-10-19 14:42:00,147,RIOS RIOS FRANCISCO FERNANDO,1,Si,2-110,Zamora.,163500,OT [01] Cuadrilla Zamora 2025-10-19 (006) FR.pdf
397406,1,REDES,Zamora barrio El Oso vía al Podocarpus se da a...,PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-14 08:00:00,2025-10-14 11:30:00,210,MORALES RIVERA LUIS ALBERTO,1,No,R-159,"Zamora, El Oso, Yantzaza",163163,OT [02] Alumbrado Zamora 2025-10-14 (012) LM.pdf

In [20]:
filter_df =  df.query("Alimentador == 'Zamora I' and Cuenta == '?' and (Tipo == 'CORRECTIVO' or Tipo == 'PREVENTIVO')")
filter_df

,Item,Cuenta,Evento,Actividad,Alimentador,Primario,Desconexion,SIG,Tipo,Materiales,...,InicioEvento,FinEvento,Duracion,Responsable,Colaboradores,HorasExtra,Vehiculo,Sitio,id_ot,Archivo
26,2,?,Zamora - Sector Parque Lineal. En el pozo Nro...,NO PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2024-01-06 11:40:00,2024-01-06 13:40:00,120,YAURE DIAZ RAMIRO GABRIEL,1,Si,2-110,Zamora,121775,OT [02] Alumbrado Zamora 2024-01-06 (013) RY.pdf
219,3,?,El Queque se confirma el buen estado el servic...,PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2019-04-15 10:22:00,2019-04-15 11:35:00,73,MORALES RIVERA LUIS ALBERTO,1,No,R-113,"El Queque, Zamora",27048,OT [01] Cuadrilla Zamora 2019-04-15 (012) LM.pdf
257,4,?,"En Zamora, Edificio de NETPLUS, se coordina co...",PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2022-01-26 09:30:00,2022-01-26 10:00:00,30,RIOS RIOS FRANCISCO FERNANDO,2,No,2-110,"Zamora, Santa Rita",80004,OT [01] Cuadrilla Zamora 2022-01-26 (006) FR.pdf
293,3,?,"El Limón, estructura. 217555 se realiza inspe...",NO PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2025-01-06 08:50:00,2025-01-06 09:30:00,40,RIOS RIOS FRANCISCO FERNANDO,2,No,2-110,"Zamora, La Fragancia",144597,OT [01] Cuadrilla Zamora 2025-01-06 (006) FR.pdf
588,10,?,Sector de La Fragancia vía antigua a Loja en l...,PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2019-10-08 14:35:00,2019-10-08 16:05:00,90,MORALES RIVERA LUIS ALBERTO,1,No,R-113,"Zamora, La Fragancia, Vía antigua a Loja",36356,OT [01] Cuadrilla Zamora 2019-10-08 (012) LM.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396937,10,?,En el Sector El Limón Bajo se realiza inspecci...,PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-14 15:45:00,2025-10-14 16:00:00,15,JARA NARVAEZ GALO SILVERIO,2,No,2-111,Zamora,163150,OT [21] Agencia Zamora 2025-10-14 (050) GJ.pdf
396986,5,?,En el Sector de Podocarpus se Restituye medido...,PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-14 13:00:00,2025-10-14 13:30:00,30,JARA NARVAEZ GALO SILVERIO,2,No,2-111,Zamora,163150,OT [21] Agencia Zamora 2025-10-14 (050) GJ.pdf
397065,2,?,Se hace recorrido revisando el alumbrado públi...,PROG,Zamora I,No,No,No,PREVENTIVO,·,...,2025-10-13 09:20:00,2025-10-13 09:50:00,30,MORALES RIVERA LUIS ALBERTO,1,No,R-159,"Zamora, Cumbaratza, Yantzaza",163069,OT [02] Alumbrado Zamora 2025-10-13 (012) LM.pdf
397081,14,?,Zamora en la calle Sevilla de oro entre Héroe...,NO PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-13 15:35:00,2025-10-13 17:01:00,86,MORALES RIVERA LUIS ALBERTO,1,No,R-159,"Zamora, Cumbaratza, Yantzaza",163069,OT [02] Alumbrado Zamora 2025-10-13 (012) LM.pdf
397263,2,?,"DAÑO REPORTADO POR Centro de Control, Calle D...",NO PROG,Zamora I,No,No,No,CORRECTIVO,·,...,2025-10-23 08:20:00,2025-10-23 10:45:00,145,RIOS RIOS FRANCISCO FERNANDO,1,No,2-110,"Zamora, San Carlos de las Minas",163749,OT [01] Cuadrilla Zamora 2025-10-23 (006) FR.pdf